### ISSUE TITLE
Check dspace/modules folder for customizations

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#610]
Check dspace/modules folder for customizations.

**Comment by alawvt** [comment]
Files in VTW DSpace 5 that are not in VTW DSpace 6, /dspace/modules/

- [x] additions/src/main/java/org/dspace/app/itemimport/itemimport.java # this was fixed in DSpace 6 with https://github.com/DSpace/DSpace/pull/1241/commits/261dee47143bc7ca31b41be92bdbf41b3bc6cce8 so this file is not needed.

- [ ] additions/src/main/java/org/dspace/authorize/AuthorizeManager.java # used for lock symbol commit, https://github.com/VTUL/vtechworks/commit/9b6d9625b390e9abc34dd4bac08ca2b775329a85, however dspace-api/src/main/java/org/dspace/authorize/AuthorizeManager.java **does not exist** in DSpace 6. Continued in Issue #571.

- [x] additions/src/main/java/org/dspace/content/DSpaceObject.java # used for OMALS submission form, https://github.com/VTUL/vtechworks/commit/28cde78849b6c58b948187f50586a6b2cc2b3957. dspace-api/src/main/java/org/dspace/content/DSpaceObject.java **does exist** in DSpace 6 however it is quite different. The OMALS submission form seems to work well enough, as is so we don't need to add this file.

- [ ] additions/src/main/resources/spring/spring-dspace-addon-sherpa-configuration-services.xml # used for Sherpa Romeo authority control, https://github.com/VTUL/vtechworks/commit/182d6b35cca5def43799e860da4dcfc3804673aa. dspace-api/src/main/resources/spring/spring-dspace-addon-sherpa-configuration-services.xml **does exist** in DSpace 6. Continued in Issue #579.

- [ ] xmlui-mirage2/src/main/webapp/themes/vtmirage2/vendor/videojs/video.js # used for video playback, https://github.com/VTUL/vtechworks/commit/c532205a0e577ef55e7cd750a5b74d85dc13fd53. @keithgee, the videos seems to play. Do we need this file?

- [ ] xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java # used for lock symbol commit, https://github.com/VTUL/vtechworks/commit/9b6d9625b390e9abc34dd4bac08ca2b775329a85, dspace-xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java **does exist** in DSpace 6. Continued in Issue #571.

- [ ] xmlui/src/main/webapp/exception2dri.xslt # used to customize error page, https://github.com/VTUL/vtechworks/commit/e1039beefadf8b94a1fc96fd8314a1dd87f1a652. dspace-xmlui/src/main/webapp/exception2dri.xslt **does exist** in DSpace 6. This should hide the Java stacktrace when an error is produced. Continued in Issue #611.


- [ ] xmlui/src/main/webapp/exception2html.xslt # used to customize error page, https://github.com/VTUL/vtechworks/commit/e1039beefadf8b94a1fc96fd8314a1dd87f1a652. dspace-xmlui/src/main/webapp/exception2html.xslt **does exist** in DSpace 6. Continued in Issue #611.

**Comment by keithgee** [comment]
@alawvt, thank you for your thoroughness in checking this. Could you open up specific issues that address any problems found in testing?

Some of these files, for example, ItemImport.java - are missing because the DSpace API and other parts of the codebase were reorganized in DSpace 6, and those files no longer exist.

It's possible that some of the customizations in these missing files have moved into other files, some of them will be addressed by currently open issues (possibly the lock and SHERPA issues), and some of them were missed during the initial migration.

That's a lot of work, but I think that having specific issues open for each piece of missing or broken functionality will help me to answer the question of "how close are we to being able to upgrade DSpace", or at least "how long until we can upgrade the Dev server for more testing" better than I have been.

Thanks!

**Comment by keithgee** [comment]
Here's a specific example:

The ItemImport.java file had this in the commit message:

```
commit c8467059b60402729dca1edde9378e44e83b290d
Author: Anne Lawrence <alaw@vt.edu>
Date:   Fri Aug 12 12:06:37 2016 -0400

    Fix SAF upload so it reads the colletions file
    This fixes the issue reported in DS-2633 and fixed in PR 1241, but
    will not be incorporated until DSpace 6. It fixes a null pointer.
```

If there's a problem with our current project in reading the collections file from the SAF upload, I'd like to have an issue open specifically for that so I know that it needs to be fixed. It could also be useful to know where this fix was made, because the fix is likely similar for the new version of the code. But in this particular case, at least,  it's less useful to know that a file is missing between versions because:
             - The fix was (presumably) included in the default version of DSpace 6 as per the commit message
             - The file that this overlay customizes doesn't exist in DSpace 6

**Comment by alawvt** [comment]
@keithgee, I agree that any issues for these files should be separate. I have listed all the files above and whether they exist in DSpace 6. Aside from the video.js question, https://github.com/VTUL/vtechworks/issues/610#issuecomment-514378747, I have created separate issues for those that still need attention. See links above
