### ISSUE TITLE
Configure OCLC Digital Collection Gateway to harvest VTechWorks for Discovery

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#710]
Continues in part,  [Enable OAI-PHM for OCLC Digital Collection Gateway #142](https://code.vt.edu/it-services/vtlibans_dspace/-/issues/142).

Use OCLC Digital Collection Gateway (DCG) to harvest VTechWorks for Discovery

- [x] Arrange for OCLC to change URL for VTechWorks from HTTP to HTTPS - @alawvt 
- [x] Create list of existing OCLC records harvested from http://vtechworks.lib.vt.edu/oai/request -OCLC 2020-07-29
- [x] Review list for items to not delete - @alawvt  
- [x] Delete old NDLTD and ETD-db repositories from DCG - OCLC 2020-07-30
- [x] Delete all existing OCLC records harvested from http://vtechworks.lib.vt.edu/oai/request except  https://virginiatech.share.worldcat.org/wms/cmnd/metadata/cataloging/edit/bib/70222828 - OCLC
- [x] Change URL from HTTP to HTTPS - OCLC
- [x] "Delete WorldCat Records" for all non-existent inactive collections
- [x] Decide if any collections should not be harvested by DCG, #712 - harvest all collections
- [x] Map ETD collections in Digital Collection Gateway, #715 
- [ ] Ask holding libraries to delete 5 old OCLC records and delete them - won't do
- [x] Improve qdc OAI-PHM crosswalk for OCLC DCG harvest, #713
- [x] Map VTechWorks content types to DCG material types, #711
- [x] Map other collections

Reference
- https://code.vt.edu/digital-research-services/VTechWorks_Documentation/-/wikis/OAI-PMH

**Comment by alawvt** [comment]
OCLC deleted all existing OCLC records harvested from http://vtechworks.lib.vt.edu/oai/request and changed the URL in DCG to HTTPS. However 5 records that they could not remove, due to other libraries having holdings on them. These were:

967160570; http://hdl.handle.net/10919/73484; 9 libraries
1004749525; http://hdl.handle.net/10919/78622; 2 libraries
1054759192; http://hdl.handle.net/10919/84848; 21 libraries
1089628300; http://hdl.handle.net/10919/86593; 9 libraries
1096208132; http://hdl.handle.net/10919/80906; 9 libraries

These records cannot be edited. They will remain in WorldCat. One option we have is to not sync those records through by removing them from your repository and instead just managing them in WorldCat.

Otherwise, you will need to contact the libraries who have a hold on the items and ask they remove the holding so the items can be deleted from WorldCat and synced back through, or else a duplicate will be made when the collection these belong to is harvested.

Thank you,

Maverik Cox
OCLC • Customer Support Consultant, Management and Customer Operations

**Comment by alawvt** [comment]
We won't ask holding libraries to delete 5 old OCLC records and delete them, since there are so many libraries and there are already other duplicates.

This issue is continued with #732.
