### ISSUE TITLE
Overview: Migrate to DSpace 7

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#810]
Continues [Plan testing and migration to DSpace 7](https://code.vt.edu/it-services/vtlibans_dspace/-/issues/173)

## Strategy

We will move to DSpace 7 as smoothly as possible, ensuring VTechWorks current functionality and user experience. For the initial migration we will not enable entities. This will allow us to migrate our existing collections hierarchy and associated metadata as-is. Once we are are on DSpace 7, we can consider enabling Person entities, which are necessary for the ORCID write integration.

## Tasks

- [x] Convert DSpace 5 to DSpace 6 SOLR stats and load - @keithgee
- [x] #811  - @alawvt  DONE
- [x] #820 - @alawvt DONE
- [x] #821 
- [x] Write a test plan/functionality requirements for DSpace 7 - @keithgee DOING
- [x] [Upgrade to Elements 6.9 which supports DSpace 7 deposit and harvest](https://code.vt.edu/digital-research-services/vtw-elements/-/issues/90) - DOING
- [x] [Create a DSpace test server](https://code.vt.edu/it-services/vtlibans_dspace/-/issues/180) vtechworks7-dev - @keithgee  DOING
- [x] #819
- [x] Connect elements-dev to vtechworks7-dev
- [x] [Create a list DSpace 7 components for server planning](https://code.vt.edu/it-services/vtlibans_dspace/-/issues/181) - @keithgee 
- [x] Plan Ansible/automation
- [x] Calculate customizations and fixes needed
- [x] Customize and fix DSpace 7
- [x] Test DSpace 7

## Timeline

- [x] 2022-06-24 DSpace 7.3 released
- [x] 2022-07 Elements 5.9 released supporting Elements harvest and deposit to DSpace 7
- [x] ? DSpace 6.4 [bug fix] released
- [x] 2022-11 DSpace 7.4 [bug fix] released 
- [x] 2023-04 DSpace 7.5 released
- [x] 2023-05-15 (end of spring semester) DSpace 7 on production
- [x] 2023-07-01 DSpace 6.x support ends

## References
[DSpace 7 Q&A Webinar (July 13, 2022)](https://docs.google.com/document/d/1_Yd3hQfmZMcaZSW_oOFMwEXjNDyRi2vk5g92Xu8ojiM/edit#heading=h.tifm2kcex3ia)
[VTechWorks wiki - DSpace 7](https://code.vt.edu/digital-research-services/VTechWorks_Documentation/-/wikis/dspace_7)
[DSpace 7.x Documentation](https://wiki.lyrasis.org/display/DSDOC7x)
[DSpace Release 7.0 Status](https://wiki.lyrasis.org/display/DSPACE/DSpace+Release+7.0+Status)

**Comment by keithgee** [comment]
We've completed the upgrade; we were about 6 months later than the original plan.
