### ISSUE TITLE
Test DSpace 7.4 on DSpace Demo

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#820]
Test the changes in DSpace 7.4 that can be tested in DSpace Demo

- [DSpace 7.4 Release Notes](https://wiki.lyrasis.org/display/DSDOC7x/Release+Notes#ReleaseNotes-7.4ReleaseNotes)
- [DSpace 7.4 announcement](https://groups.google.com/g/dspace-community/c/AyYrIz93otw)

**Comment by alawvt** [comment]
- [x] [Add thumbnail to Search list view #1744](https://github.com/DSpace/dspace-angular/issues/1744) - resolved in 7.4
- [x] [Add thumbnail to Browse #1745](https://github.com/DSpace/dspace-angular/issues/1745) -resolved in 7.4
- [x] [Edit Item > Authorizations > Policy Group change does not appear #1753 ](https://github.com/DSpace/dspace-angular/issues/1753) - resolved in 7.4
- [x] [Preserve line breaks in metadata #1762](https://github.com/DSpace/dspace-angular/issues/1762)  - resolved in 7.4
- [x] [Display line breaks in metadata #1763](https://github.com/DSpace/dspace-angular/issues/1763)  - resolved in 7.4 - line breaks display, HTML display.
- [x]  ["Recently Added Items" doesn't exist on homepage & community pages #667](https://github.com/DSpace/dspace-angular/issues/667) - resolved in 7.4 - recent items appear on home page but not community page - created follow up issue, [Add "Recently Added Items" to Community pages #1901](https://github.com/DSpace/dspace-angular/issues/1901)
